name: 'ShareSettings - {{NAME}}'
description: '{{NAME}} の共通ファイルを展開先にコピーする'

inputs:
  target_dir:
    description: '展開先ディレクトリのパス'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: 展開先ディレクトリを作成
      shell: bash
      run: mkdir -p "${{ inputs.target_dir }}"

    - name: 共通ファイルをコピー
      shell: bash
      run: cp -a "${{ github.action_path }}/shared-files/." "${{ inputs.target_dir }}/"
